menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/Lamply

favicon: /mugen.ico
logo: /mugen.ico

# Comment
# e.g disqus: seansun
disqus: https-lamply-github-io
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
